# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f82de32d05b5f7d1e40149aa9e5b72a47862a4ad194be97d74a7ed78bdf7ce324f9a4e81189f833bb0e2d842a1fd59baec1228b58b7c69516bbc57f8847ad946

test:
  secret_key_base: 0f25750a0c6fbced5a236fac64f191d45fe9f9421ed2664b37eb78b01b8344f34d40978c7e07945038d3fce51e8f7165bb7ec1b036c422102c21ceb10384f3d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
